apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: rpaasplans.extensions.tsuru.io
spec:
  group: extensions.tsuru.io
  names:
    kind: RpaasPlan
    listKind: RpaasPlanList
    plural: rpaasplans
    singular: rpaasplan
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
